package com.abhi.kotlinnotesmvvm.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room annotation
 * @Entity (tableName=) : create a table with name
 * @ColumnInfo(name=) : rename col. Default name is same as variable name.
 * @PrimaryKey(autoGenerated=) mark col as primary key.
 * */

@Entity(tableName = "note_table")
class Note(
    var title: String,
    var description: String,
    var priority: Int) {

    @PrimaryKey(autoGenerate = true)
    var id: Int = 0
}